### ISSUE TITLE
Can this library be used to modify server response?

### ISSUE THREAD

**Issue by jesuslpm** [titanium007/Titanium#1]
Please see this question on StackExchange:

http://sharepoint.stackexchange.com/questions/133091/soapexception-possible-soap-version-mismatch-accessing-ssl-enabled-site

Can this library be used to do the same I do with FidllerCore?

Thank you

**Comment by titanium007** [comment]
Yes. you can modify both request and response. If you look at the code there are two call backs

BeforeRequest &
AfterRequest

See example below.

https://github.com/titanium007/Titanium/blob/master/Titanium.ProxyTest/ProxyTestController.cs
