### ISSUE TITLE
HttpSession response is not working as expected

### ISSUE THREAD

**Issue by simha9000** [titanium007/Titanium#11]
If a HTTP service request is an asynchronus one, am always getting its response bytes content length as -1.

**Comment by titanium007** [comment]
Can you elaborate? If response is chunked we don't have a way to estimate the content length. That's why its -1.

**Comment by simha9000** [comment]
But... As per the code you are waiting for the session complete event... Which is not happening.
Session means we get data in chunked mode itself. As the code has Session handling, I have asked you this question...

Sent from my Windows Phone
________________________________

**Comment by titanium007** [comment]
Sorry for the inconvenience. I never intended to expose HttpWebRequest & HttpWebResponse in the Api. That causes confusion. Modifying or reading content length would be locked in future release.

**Comment by simha9000** [comment]
That's ok... Not a problem...
Thanks for the response...
But it would be good... If u add the session
Based tracing... By avoiding modifications of http web requests, because it exactly behaves like a fiddler tool.
If you know how to approach it... Please suggest me.. I will try to implement.

Thanks in advance...

Sent from my Windows Phone
________________________________

**Comment by titanium007** [comment]
The problem is performance. If you decide to decode every response, irrespective of whether the user needs it, then we could lose a lot of CPU power and memory. So I decided to allow the user to  first check if he needs to read the response body. If not I simply stream the response body bytes directly to client without touching it.

Fiddler is a different tool, the key attribute of FiddlerCore isn't performance (which is fine)-- it's instead compatibility for debugging web requests. 

This was designed as a light weight proxy for single computer to block or modify response.

**Comment by simha9000** [comment]
Oh! That's nice...
But performance is not the criteria to me, I just want to grab the bytes of data that is been given by an wcf.. Which sends data in chunks

Sent from my Windows Phone
________________________________

**Comment by titanium007** [comment]
If you want to received the data as bytes, you can do the following.

````public void OnResponse(object sender, SessionEventArgs e)
	{
		 
             //modify response headers
            var responseHeaders = e.ResponseHeaders;

            if (e.ResponseStatusCode == HttpStatusCode.OK)
            {
                if (e.ResponseContentType.Trim().ToLower().Contains("text/html"))
                {
                    //Get/Set response body bytes
                    byte[] responseBodyBytes = e.GetResponseBody();
                    e.SetResponseBody(responseBodyBytes);

                    //Get response body as string
                    string responseBody = e.GetResponseBodyAsString();

                    //Inject script in to body
                    Regex rex = new Regex("</body>", RegexOptions.RightToLeft | RegexOptions.IgnoreCase | RegexOptions.Multiline);
                    string modified = rex.Replace(responseBody, "<script type =\"text/javascript\">alert('Response was modified by this script!');</script></body>", 1);

                    //Set modifed response Html Body
                    e.SetResponseBodyString(modified);
                }
            }
	}
