### ISSUE TITLE
Converting socks5 proxy to http(s) proxy?

### ISSUE THREAD

**Issue by huhu2207** [titanium007/Titanium#12]
Hi there,

Is it possible to use directly, or slightly modify this library to let it "convert" a SOCKS5 proxy to HTTP proxy?

Regards,
Jackson Hu.

**Comment by titanium007** [comment]
I never worked with socks proxy before.

However I think you can route any packets that involves HTTP request (check if the packet stream content starts with HTTP methods like GET, CONNECT) to this proxy.

**Comment by huhu2207** [comment]
Okay thanks for that.
