### ISSUE TITLE
Freezing and can not open a web site

### ISSUE THREAD

**Issue by LostMann** [titanium007/Titanium#16]
Hi,

When i am using the proxy i cannot open the http://www.haberler.com and also http://www.yemeksepeti.com. I try to debug but i can not find the problem. Chrome ask for kill the web site or wait for but never opens the site.

Thanks.

**Comment by LostMann** [comment]
Hi, 

Thanks for fast response, in chrome or other browsers this patch is working but when you test in IE it freezes again. I think for IE it has a diffrent solution.

Ty.

**Comment by titanium007** [comment]
Can you elaborate? I don't see a  problem with IE. Notice that my IE version is 11 (default for Win 7)

![capture](https://cloud.githubusercontent.com/assets/2637679/10414315/4af27b68-6f9c-11e5-9f45-9707866d49e8.PNG)
![capture1](https://cloud.githubusercontent.com/assets/2637679/10414316/4b0331ec-6f9c-11e5-9278-7f21467233cc.PNG)

**Comment by LostMann** [comment]
him i see. i converted the project to .net 3.5. may be because of this didnt work. i will convert to .net 4.0 and i will try again so. my ie version is same too but i am using win10. i am going to try now.



Sent from my Mi phoneOn titanium007 <notifications@github.com>, 11 Oct 2015 05:16 wrote:Can you elaborate? I don't see a  problem with IE. Notice that my IE version is 11 (default for Win 7)

**Comment by LostMann** [comment]
Wierd, it is working in my project too :( Sorry for that i couldnt understand that. I tested in my laptop first. The page didnt open in IE. Now i am trying on my desktop it is working now. Sorry for wrong that. You can close the issue. Thanks for help.

Date: Sun, 11 Oct 2015 13:38:27 +0300
Subject: Re: [Titanium] Freezing and can not open a web site (#16)
From: s_sarigul@hotmail.com
To: reply@reply.github.com; Titanium@noreply.github.com

him i see. i converted the project to .net 3.5. may be because of this didnt work. i will convert to .net 4.0 and i will try again so. my ie version is same too but i am using win10. i am going to try now.







Sent from my Mi phoneOn titanium007 <notifications@github.com>, 11 Oct 2015 05:16 wrote:

Can you elaborate? I don't see a  problem with IE. Notice that my IE version is 11 (default for Win 7)

**Comment by titanium007** [comment]
Thanks.
