### ISSUE TITLE
Filtering URLs

### ISSUE THREAD

**Issue by emert117** [titanium007/Titanium#3]
I try to block some URLs. I am developing a free ( and open source) web browser for kids.
ProxyTestController.cs -> OnRequest -> e.Cancel = true doesn't work. 
What is the best way to block URLs and show a warning page?

Thanks.

**Comment by titanium007** [comment]
If you look at the sample project.

https://github.com/titanium007/Titanium/blob/master/Titanium.Web.Proxy.Test/ProxyTestController.cs

Specifically look at the OnResponse Event. There you can modify the html content of the response to what ever you want to. 

I am still cleaning up the code e.Cancel was something not to be exposed to developer.

**Comment by emert117** [comment]
Hi, thank you for the answer.
I can detect URL and HTML string at ProxyTestController.cs -> OnResponse from e.RequestURL and e.ResponseString. And i can change ResponseString.
But i think requested page is already loaded. I want no connection if requested URL is in blacklist.

**Comment by titanium007** [comment]
Okay. I modified the code just now. I think you could do something line below on OnRequest handler.

```csharp
 if(e.RequestURL.Contains("jw.org"))
 {
    e.Ok("<!DOCTYPE html><html><body><h1>Blocked</h1><p>website blocked.</p></body></html>");
 }
```

**Comment by emert117** [comment]
I tried code, but it doesn't work, web site is being loaded. I cleaned  browser cache.

**Comment by titanium007** [comment]
Are you sure. I just tried and worked for me. May be you are not pointing the browser to the proxy.

````C#
   public void OnRequest(object sender, SessionEventArgs e)
        {
            if (e.RequestURL.Contains("somewebsite.com"))
            {
                e.Ok("<!DOCTYPE html><html><body><h1>Blocked</h1><p>website blocked.</p></body></html>");
            }
        }

````

**Comment by emert117** [comment]
It works. I added it to first lines of OnRequest. Thanks.
