### ISSUE TITLE
SSL Certificate

### ISSUE THREAD

**Issue by emert117** [titanium007/Titanium#5]
In some https web sites, i got error. If i buy a SSL certifiicate, can i solve this problem?

**Comment by titanium007** [comment]
I not sure. Can you give me a test case. You don't need to buy anything in any case. Usually if the certificate of the website you are browsing is not valid then request will fail.

**Comment by emert117** [comment]
Google.com login page and youtube.com fails. I thought buying an SSL certificate could solve the problem.

**Comment by titanium007** [comment]
Did any other https:// pages ever succeed? Both youtube and google works for me. 

It may be that you have not installed the certificate in your machine. (Both on Personal & trusted root certificate stores). You can use certmgr.msc. The proxy should install it if you enable SSL.  Basically the proxy uses this certificate to issue certificates to websites like google and youtube. For that to work you should install it in your machine. (The computer should trust this fake root certificate, in effect the computer will trust all certificate signed by this root certificate) . This is just a test root certificate. You can generate your own Root Certficate (Self-signed) instead (use makecert.exe)

https://github.com/titanium007/Titanium/blob/master/Titanium.Web.Proxy/DO_NOT_TRUST_FiddlerRoot.cer

**Comment by emert117** [comment]
I installed certificates to personal and trusted root, enabled ssl on app. But i still get erros.

![personelcer](https://cloud.githubusercontent.com/assets/10380890/8395092/c83cba48-1d62-11e5-9039-f360c36f6030.png)
![screen](https://cloud.githubusercontent.com/assets/10380890/8395091/c83cb3ae-1d62-11e5-8e6a-8f6a12cbfcfe.png)
![trustedcer](https://cloud.githubusercontent.com/assets/10380890/8395093/c84034a2-1d62-11e5-9567-cae562ecfbe9.png)

**Comment by titanium007** [comment]
Can you put a break point in visual studio and find out where it is throwing error if any. Also make sure the proxy settings are correct.

![capture](https://cloud.githubusercontent.com/assets/2637679/8395114/34b47cf8-1d2a-11e5-9869-6c07929c0025.JPG)
![capture1](https://cloud.githubusercontent.com/assets/2637679/8395115/34ccc63c-1d2a-11e5-8e91-b9550accbdc7.JPG)

**Comment by emert117** [comment]
I checked proxy settings. I opened Google home page without problems. When I tried to login to Google, I got this screen.:
![image](https://cloud.githubusercontent.com/assets/10380890/8395133/7a682254-1d66-11e5-81a0-ad7ad442cd0d.png)

Another siimilar image(not my pc just for english explanation)
![image](https://cloud.githubusercontent.com/assets/10380890/8395137/e09fb424-1d66-11e5-9eb1-4171bb3efc07.png)

**Comment by titanium007** [comment]
To be honest, I have no idea what this error means. I used chrome and my gmail works fine. Make sure firewall is allowing proxy to listen.

Its late night. I will reply back if I find anything later. 

![capture](https://cloud.githubusercontent.com/assets/2637679/8395162/32cae0f0-1d2d-11e5-9297-45f5e3063227.JPG)

**Comment by titanium007** [comment]
As it appears this looks like not an issue with the proxy itself. Some settings in the machine is wrong. I am going to close this.

The proxy works fine one the machines I tested.

**Comment by emert117** [comment]
I tested code on different computers. I got the same problem. I don't know what causes the problem. 
Thank you
