### ISSUE TITLE
How to read request data?

### ISSUE THREAD

**Issue by mergoktas** [titanium007/Titanium#7]
1.How to read the send data? I need to read the submitted form data sent by normal html submit or by ajax call.

2.For certain Url(s), how to avoid connection? Kind of filtering.

By the way, really very good work. Thanks for sharing.

Muharrem

**Comment by emert117** [comment]
2) ProxyTestController -> OnRequest ->
 if (e.RequestURL == "www.example.com")
{
        e.Ok("<html><body><h1> Banned </h1></body></html>");
}

**Comment by mergoktas** [comment]
I think, I found the way for my question 1).

ProxyTestController -> OnRequest ->
char[] buf = new char[e.RequestLength];
e.ClientStreamReader.Read(buf, 0, e.RequestLength);
 string s = new string(buf);

And thanks to emert117 for his response. I will close this issue.
